---

- name: Update APT cache
  apt:
    update_cache: yes

- name: Install Vector package from existing repo
  apt:
    name: vector
    state: present

- name: Copy Vector config from template
  template:
    src: "{{ vector_template }}"
    dest: "{{ vector_config_file }}"
    mode: 0644
  when: vector_config_type == 'template'
  notify: restart vector

- name: Copy Vector static config file
  copy:
    src: "{{ vector_static_config_file }}"
    dest: "{{ vector_config_file }}"
    mode: 0644
  when: vector_config_type == 'static'
  notify: restart vector

- name: Ensure VECTOR_CONFIG is set in /etc/default/vector
  lineinfile:
    path: /etc/default/vector
    line: "VECTOR_CONFIG={{ vector_config_file }}"
    state: present

- name: Start and enable Vector service
  service:
    name: vector
    state: started
    enabled: yes
